
# Build the application 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env 
WORKDIR /app

COPY ServerAsp.csproj /app
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

# Build the image 
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Port
EXPOSE 80

# EntryPoint

ENTRYPOINT [ "dotnet", "ServerAsp.dll" ]